name: FileCodeBox Builder

on:
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: "Original Tag for checkout (e.g. V2.3)"
        required: true
        type: string
      docker_tag:
        description: "Formatted Tag for Docker (e.g. v2.3.0)"
        required: true
        type: string

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/filecodebox
  UPSTREAM_REPO: vastsa/FileCodeBox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          ref: ${{ inputs.upstream_ref }}
          path: build_context

      - name: Modify Timezone to Toronto
        run: |
          cd build_context
          sed -i 's|Asia/Shanghai|America/Toronto|g' Dockerfile
          sed -i 's|LABEL author=".*"|LABEL author="Kyxie"|g' Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: build_context
          file: build_context/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.docker_tag }}
            ${{ env.REGISTRY_IMAGE }}:latest
          cache-from: type=gha,scope=filecodebox
          cache-to: type=gha,mode=max,scope=filecodebox
          provenance: false
